#!/usr/bin/env bash
set -euxo pipefail

# Variables injected by Terraform templatefile
REPO_URL="${github_repo_url}"
REPO_DIR="${repo_dir}"
COMPOSE_ENV="${compose_env}"
COMPOSE_VERSION="${docker_compose_ver}"
AWS_REGION="${aws_region}"
SSM_DB_PASSWORD="${ssm_db_password}"
SSM_JWT_SECRET="${ssm_jwt_secret}"
SSM_AIRS_API_TOKEN="${ssm_airs_api_token}"
SSM_AIRS_API_URL="${ssm_airs_api_url}"
SSM_AIRS_PROFILE="${ssm_airs_profile}"
SSM_VERTEX_API_KEY="${ssm_vertex_api_key}"
SSM_ANTHROPIC_KEY="${ssm_anthropic_key}"
SSM_AZURE_ENDPOINT="${ssm_azure_endpoint}"
SSM_AZURE_API_KEY="${ssm_azure_api_key}"
SSM_OLLAMA_API_URL="${ssm_ollama_api_url}"

echo "==> Updating packages"
dnf update -y

echo "==> Installing Docker, Git, AWS CLI"
dnf install -y docker git awscli
systemctl enable --now docker
usermod -aG docker ec2-user || true

echo "==> Installing docker-compose $${COMPOSE_VERSION}"
curl -L "https://github.com/docker/compose/releases/download/$${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

echo "==> Cloning repo $${REPO_URL}"
rm -rf "$${REPO_DIR}"
git clone "$${REPO_URL}" "$${REPO_DIR}"
cd "$${REPO_DIR}"

AWS_DEFAULT_REGION="$${AWS_REGION}"
export AWS_DEFAULT_REGION

fetch_ssm() {
  local name="$1"
  local required="$2"
  if [ -z "$${name}" ]; then
    if [ "$${required}" = "true" ]; then
      echo "Missing required SSM parameter name" >&2
      exit 1
    fi
    echo ""
    return 0
  fi
  local value
  if value=$(aws ssm get-parameter --name "$${name}" --with-decryption --query 'Parameter.Value' --output text 2>/tmp/ssm_err); then
    echo "$${value}"
  else
    if [ "$${required}" = "true" ]; then
      echo "Required SSM parameter $${name} not found or unreadable" >&2
      cat /tmp/ssm_err >&2 || true
      exit 1
    fi
    echo ""
  fi
}

DB_PASS=$(fetch_ssm "$${SSM_DB_PASSWORD}" true)
JWT_SECRET_GEN=$(fetch_ssm "$${SSM_JWT_SECRET}" true)
AIRS_API_URL_VAL=$(fetch_ssm "$${SSM_AIRS_API_URL}" false)
AIRS_API_TOKEN_VAL=$(fetch_ssm "$${SSM_AIRS_API_TOKEN}" false)
AIRS_PROFILE_VAL=$(fetch_ssm "$${SSM_AIRS_PROFILE}" false)
VERTEX_API_KEY_VAL=$(fetch_ssm "$${SSM_VERTEX_API_KEY}" false)
ANTHROPIC_KEY_VAL=$(fetch_ssm "$${SSM_ANTHROPIC_KEY}" false)
AZURE_ENDPOINT_VAL=$(fetch_ssm "$${SSM_AZURE_ENDPOINT}" false)
AZURE_API_KEY_VAL=$(fetch_ssm "$${SSM_AZURE_API_KEY}" false)
OLLAMA_API_URL_VAL=$(fetch_ssm "$${SSM_OLLAMA_API_URL}" false)

echo "==> Writing env files from SSM values"
cat > .env.database <<EOF
# Auto-generated by user_data.sh from SSM
POSTGRES_DB=shop_assist
POSTGRES_USER=admin
POSTGRES_PASSWORD=$${DB_PASS}
EOF

cat > .env.backend <<EOF
# Auto-generated by user_data.sh from SSM
BACKEND_PORT=3001
FRONTEND_URL=http://localhost
DATABASE_URL=postgresql://admin:$${DB_PASS}@postgres:5432/shop_assist
JWT_SECRET=$${JWT_SECRET_GEN}

# Optional provider configs (leave empty to use mocks)
AIRS_API_URL=$${AIRS_API_URL_VAL}
AIRS_API_TOKEN=$${AIRS_API_TOKEN_VAL}
AIRS_PROFILE_NAME=$${AIRS_PROFILE_VAL}
VERTEX_PROJECT_ID=
VERTEX_LOCATION=us-central1
VERTEX_API_KEY=$${VERTEX_API_KEY_VAL}
ANTHROPIC_API_KEY=$${ANTHROPIC_KEY_VAL}
AZURE_OPENAI_ENDPOINT=$${AZURE_ENDPOINT_VAL}
AZURE_OPENAI_API_KEY=$${AZURE_API_KEY_VAL}
AZURE_OPENAI_DEPLOYMENT=gpt-4
OLLAMA_API_URL=$${OLLAMA_API_URL_VAL}
OLLAMA_MODEL=mistral

# Rate limiting defaults
RATE_LIMIT_MAX_RETRIES=3
RATE_LIMIT_INITIAL_DELAY=1000
RATE_LIMIT_MAX_DELAY=60000
RATE_LIMIT_BACKOFF_MULTIPLIER=2
EOF

cat > .env <<EOF
# Auto-generated by user_data.sh from SSM (shared secrets/providers)
JWT_SECRET=$${JWT_SECRET_GEN}

# Optional provider configs (leave empty to use mocks)
AIRS_API_URL=$${AIRS_API_URL_VAL}
AIRS_API_TOKEN=$${AIRS_API_TOKEN_VAL}
AIRS_PROFILE_NAME=$${AIRS_PROFILE_VAL}
VERTEX_PROJECT_ID=
VERTEX_LOCATION=us-central1
VERTEX_API_KEY=$${VERTEX_API_KEY_VAL}
ANTHROPIC_API_KEY=$${ANTHROPIC_KEY_VAL}
AZURE_OPENAI_ENDPOINT=$${AZURE_ENDPOINT_VAL}
AZURE_OPENAI_API_KEY=$${AZURE_API_KEY_VAL}
AZURE_OPENAI_DEPLOYMENT=gpt-4
OLLAMA_API_URL=$${OLLAMA_API_URL_VAL}
OLLAMA_MODEL=mistral

# Rate limiting defaults
RATE_LIMIT_MAX_RETRIES=3
RATE_LIMIT_INITIAL_DELAY=1000
RATE_LIMIT_MAX_DELAY=60000
RATE_LIMIT_BACKOFF_MULTIPLIER=2
EOF

cat > .env.frontend <<EOF
# Auto-generated by user_data.sh
VITE_BACKEND_URL=/api
EOF

echo "==> Pulling images (if any)"
$${COMPOSE_ENV} docker-compose pull || true

echo "==> Starting stack"
$${COMPOSE_ENV} docker-compose up -d

echo "==> Done. Containers running with restart policy from compose."
